# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='index',
            field=models.IntegerField(default=1, verbose_name='排列顺序'),
        ),
    ]
